apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
    app.kubernetes.io/name: scaletestapp
    app.kubernetes.io/part-of: insuretech
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: scaletestapp
