apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
    release: kube-prometheus-stack
    app.kubernetes.io/name: scaletestapp
    app.kubernetes.io/part-of: insuretech
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
