apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
    app.kubernetes.io/name: scaletestapp
    app.kubernetes.io/part-of: insuretech
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: scaletestapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
